<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Stock_Exchange.Persistance</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Stock-Exchange.Application\Stock-Exchange.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configurations\" />
    <Folder Include="Migrations\" />
    <Folder Include="Seeding\" />
  </ItemGroup>

</Project>
