using Microsoft.EntityFrameworkCore;
using Stock_Exchange.Domain.Entities;

namespace Stock_Exchange.Persistance.Seeding
{
    public static class CountrySeeder
    {
        public static async Task SeedCountriesAsync(StockExchangeDbContext context)
        {
            if (await context.Countries.AnyAsync())
            {
                return;
            }

            var countries = GetCountries();
            await context.Countries.AddRangeAsync(countries);
            await context.SaveChangesAsync();
        }

        public static IReadOnlyList<Country> GetCountries() => new List<Country>
        {
            new Country { CountryEnName = "Afghanistan", CountryArName = "أفغانستان", Code = "+93" },
            new Country { CountryEnName = "Albania", CountryArName = "ألبانيا", Code = "+355" },
            new Country { CountryEnName = "Algeria", CountryArName = "الجزائر", Code = "+213" },
            new Country { CountryEnName = "American Samoa", CountryArName = "ساموا الأمريكية", Code = "+1684" },
            new Country { CountryEnName = "Andorra", CountryArName = "أندورا", Code = "+376" },
            new Country { CountryEnName = "Angola", CountryArName = "أنغولا", Code = "+244" },
            new Country { CountryEnName = "Anguilla", CountryArName = "أنغويلا", Code = "+1264" },
            new Country { CountryEnName = "Antigua and Barbuda", CountryArName = "أنتيغوا وبربودا", Code = "+1268" },
            new Country { CountryEnName = "Argentina", CountryArName = "الأرجنتين", Code = "+54" },
            new Country { CountryEnName = "Armenia", CountryArName = "أرمينيا", Code = "+374" },
            new Country { CountryEnName = "Aruba", CountryArName = "أروبا", Code = "+297" },
            new Country { CountryEnName = "Australia", CountryArName = "أستراليا", Code = "+61" },
            new Country { CountryEnName = "Austria", CountryArName = "النمسا", Code = "+43" },
            new Country { CountryEnName = "Azerbaijan", CountryArName = "أذربيجان", Code = "+994" },
            new Country { CountryEnName = "Bahamas", CountryArName = "جزر البهاما", Code = "+1242" },
            new Country { CountryEnName = "Bahrain", CountryArName = "البحرين", Code = "+973" },
            new Country { CountryEnName = "Bangladesh", CountryArName = "بنغلاديش", Code = "+880" },
            new Country { CountryEnName = "Barbados", CountryArName = "بربادوس", Code = "+1246" },
            new Country { CountryEnName = "Belarus", CountryArName = "بيلاروسيا", Code = "+375" },
            new Country { CountryEnName = "Belgium", CountryArName = "بلجيكا", Code = "+32" },
            new Country { CountryEnName = "Belize", CountryArName = "بليز", Code = "+501" },
            new Country { CountryEnName = "Benin", CountryArName = "بنين", Code = "+229" },
            new Country { CountryEnName = "Bermuda", CountryArName = "برمودا", Code = "+1441" },
            new Country { CountryEnName = "Bhutan", CountryArName = "بوتان", Code = "+975" },
            new Country { CountryEnName = "Bolivia", CountryArName = "بوليفيا", Code = "+591" },
            new Country { CountryEnName = "Bosnia and Herzegovina", CountryArName = "البوسنة والهرسك", Code = "+387" },
            new Country { CountryEnName = "Botswana", CountryArName = "بوتسوانا", Code = "+267" },
            new Country { CountryEnName = "Brazil", CountryArName = "البرازيل", Code = "+55" },
            new Country { CountryEnName = "British Virgin Islands", CountryArName = "جزر العذراء البريطانية", Code = "+1284" },
            new Country { CountryEnName = "Brunei", CountryArName = "بروناي", Code = "+673" },
            new Country { CountryEnName = "Bulgaria", CountryArName = "بلغاريا", Code = "+359" },
            new Country { CountryEnName = "Burkina Faso", CountryArName = "بوركينا فاسو", Code = "+226" },
            new Country { CountryEnName = "Burundi", CountryArName = "بوروندي", Code = "+257" },
            new Country { CountryEnName = "Cabo Verde", CountryArName = "الرأس الأخضر", Code = "+238" },
            new Country { CountryEnName = "Cambodia", CountryArName = "كمبوديا", Code = "+855" },
            new Country { CountryEnName = "Cameroon", CountryArName = "الكاميرون", Code = "+237" },
            new Country { CountryEnName = "Canada", CountryArName = "كندا", Code = "+1" },
            new Country { CountryEnName = "Cayman Islands", CountryArName = "جزر كايمان", Code = "+1345" },
            new Country { CountryEnName = "Central African Republic", CountryArName = "جمهورية أفريقيا الوسطى", Code = "+236" },
            new Country { CountryEnName = "Chad", CountryArName = "تشاد", Code = "+235" },
            new Country { CountryEnName = "Chile", CountryArName = "تشيلي", Code = "+56" },
            new Country { CountryEnName = "China", CountryArName = "الصين", Code = "+86" },
            new Country { CountryEnName = "Colombia", CountryArName = "كولومبيا", Code = "+57" },
            new Country { CountryEnName = "Comoros", CountryArName = "جزر القمر", Code = "+269" },
            new Country { CountryEnName = "Congo", CountryArName = "جمهورية الكونغو", Code = "+242" },
            new Country { CountryEnName = "DR Congo", CountryArName = "جمهورية الكونغو الديمقراطية", Code = "+243" },
            new Country { CountryEnName = "Cook Islands", CountryArName = "جزر كوك", Code = "+682" },
            new Country { CountryEnName = "Costa Rica", CountryArName = "كوستاريكا", Code = "+506" },
            new Country { CountryEnName = "Croatia", CountryArName = "كرواتيا", Code = "+385" },
            new Country { CountryEnName = "Cuba", CountryArName = "كوبا", Code = "+53" },
            new Country { CountryEnName = "Curacao", CountryArName = "كوراساو", Code = "+599" },
            new Country { CountryEnName = "Cyprus", CountryArName = "قبرص", Code = "+357" },
            new Country { CountryEnName = "Czech Republic", CountryArName = "جمهورية التشيك", Code = "+420" },
            new Country { CountryEnName = "Denmark", CountryArName = "الدنمارك", Code = "+45" },
            new Country { CountryEnName = "Djibouti", CountryArName = "جيبوتي", Code = "+253" },
            new Country { CountryEnName = "Dominica", CountryArName = "دومينيكا", Code = "+1767" },
            new Country { CountryEnName = "Dominican Republic", CountryArName = "جمهورية الدومينيكان", Code = "+1809" },
            new Country { CountryEnName = "Ecuador", CountryArName = "الإكوادور", Code = "+593" },
            new Country { CountryEnName = "Egypt", CountryArName = "مصر", Code = "+20" },
            new Country { CountryEnName = "El Salvador", CountryArName = "السلفادور", Code = "+503" },
            new Country { CountryEnName = "Equatorial Guinea", CountryArName = "غينيا الاستوائية", Code = "+240" },
            new Country { CountryEnName = "Eritrea", CountryArName = "إريتريا", Code = "+291" },
            new Country { CountryEnName = "Estonia", CountryArName = "إستونيا", Code = "+372" },
            new Country { CountryEnName = "Eswatini", CountryArName = "إي سواتيني", Code = "+268" },
            new Country { CountryEnName = "Ethiopia", CountryArName = "إثيوبيا", Code = "+251" },
            new Country { CountryEnName = "Faroe Islands", CountryArName = "جزر فارو", Code = "+298" },
            new Country { CountryEnName = "Fiji", CountryArName = "فيجي", Code = "+679" },
            new Country { CountryEnName = "Finland", CountryArName = "فنلندا", Code = "+358" },
            new Country { CountryEnName = "France", CountryArName = "فرنسا", Code = "+33" },
            new Country { CountryEnName = "French Guiana", CountryArName = "غويانا الفرنسية", Code = "+594" },
            new Country { CountryEnName = "French Polynesia", CountryArName = "بولينيزيا الفرنسية", Code = "+689" },
            new Country { CountryEnName = "Gabon", CountryArName = "الغابون", Code = "+241" },
            new Country { CountryEnName = "Gambia", CountryArName = "غامبيا", Code = "+220" },
            new Country { CountryEnName = "Georgia", CountryArName = "جورجيا", Code = "+995" },
            new Country { CountryEnName = "Germany", CountryArName = "ألمانيا", Code = "+49" },
            new Country { CountryEnName = "Ghana", CountryArName = "غانا", Code = "+233" },
            new Country { CountryEnName = "Gibraltar", CountryArName = "جبل طارق", Code = "+350" },
            new Country { CountryEnName = "Greece", CountryArName = "اليونان", Code = "+30" },
            new Country { CountryEnName = "Greenland", CountryArName = "غرينلاند", Code = "+299" },
            new Country { CountryEnName = "Grenada", CountryArName = "غرينادا", Code = "+1473" },
            new Country { CountryEnName = "Guadeloupe", CountryArName = "غوادلوب", Code = "+590" },
            new Country { CountryEnName = "Guam", CountryArName = "غوام", Code = "+1671" },
            new Country { CountryEnName = "Guatemala", CountryArName = "غواتيمالا", Code = "+502" },
            new Country { CountryEnName = "Guernsey", CountryArName = "غيرنزي", Code = "+44" },
            new Country { CountryEnName = "Guinea", CountryArName = "غينيا", Code = "+224" },
            new Country { CountryEnName = "Guinea-Bissau", CountryArName = "غينيا بيساو", Code = "+245" },
            new Country { CountryEnName = "Guyana", CountryArName = "غيانا", Code = "+592" },
            new Country { CountryEnName = "Haiti", CountryArName = "هايتي", Code = "+509" },
            new Country { CountryEnName = "Honduras", CountryArName = "هندوراس", Code = "+504" },
            new Country { CountryEnName = "Hong Kong", CountryArName = "هونغ كونغ", Code = "+852" },
            new Country { CountryEnName = "Hungary", CountryArName = "المجر", Code = "+36" },
            new Country { CountryEnName = "Iceland", CountryArName = "آيسلندا", Code = "+354" },
            new Country { CountryEnName = "India", CountryArName = "الهند", Code = "+91" },
            new Country { CountryEnName = "Indonesia", CountryArName = "إندونيسيا", Code = "+62" },
            new Country { CountryEnName = "Iran", CountryArName = "إيران", Code = "+98" },
            new Country { CountryEnName = "Iraq", CountryArName = "العراق", Code = "+964" },
            new Country { CountryEnName = "Ireland", CountryArName = "أيرلندا", Code = "+353" },
            new Country { CountryEnName = "Isle of Man", CountryArName = "جزيرة مان", Code = "+44" },
            new Country { CountryEnName = "Italy", CountryArName = "إيطاليا", Code = "+39" },
            new Country { CountryEnName = "Ivory Coast", CountryArName = "ساحل العاج", Code = "+225" },
            new Country { CountryEnName = "Jamaica", CountryArName = "جامايكا", Code = "+1876" },
            new Country { CountryEnName = "Japan", CountryArName = "اليابان", Code = "+81" },
            new Country { CountryEnName = "Jersey", CountryArName = "جيرزي", Code = "+44" },
            new Country { CountryEnName = "Jordan", CountryArName = "الأردن", Code = "+962" },
            new Country { CountryEnName = "Kazakhstan", CountryArName = "كازاخستان", Code = "+7" },
            new Country { CountryEnName = "Kenya", CountryArName = "كينيا", Code = "+254" },
            new Country { CountryEnName = "Kiribati", CountryArName = "كيريباتي", Code = "+686" },
            new Country { CountryEnName = "Kosovo", CountryArName = "كوسوفو", Code = "+383" },
            new Country { CountryEnName = "Kuwait", CountryArName = "الكويت", Code = "+965" },
            new Country { CountryEnName = "Kyrgyzstan", CountryArName = "قيرغيزستان", Code = "+996" },
            new Country { CountryEnName = "Laos", CountryArName = "لاوس", Code = "+856" },
            new Country { CountryEnName = "Latvia", CountryArName = "لاتفيا", Code = "+371" },
            new Country { CountryEnName = "Lebanon", CountryArName = "لبنان", Code = "+961" },
            new Country { CountryEnName = "Lesotho", CountryArName = "ليسوتو", Code = "+266" },
            new Country { CountryEnName = "Liberia", CountryArName = "ليبيريا", Code = "+231" },
            new Country { CountryEnName = "Libya", CountryArName = "ليبيا", Code = "+218" },
            new Country { CountryEnName = "Liechtenstein", CountryArName = "ليختنشتاين", Code = "+423" },
            new Country { CountryEnName = "Lithuania", CountryArName = "ليتوانيا", Code = "+370" },
            new Country { CountryEnName = "Luxembourg", CountryArName = "لوكسمبورغ", Code = "+352" },
            new Country { CountryEnName = "Macau", CountryArName = "ماكاو", Code = "+853" },
            new Country { CountryEnName = "Madagascar", CountryArName = "مدغشقر", Code = "+261" },
            new Country { CountryEnName = "Malawi", CountryArName = "مالاوي", Code = "+265" },
            new Country { CountryEnName = "Malaysia", CountryArName = "ماليزيا", Code = "+60" },
            new Country { CountryEnName = "Maldives", CountryArName = "جزر المالديف", Code = "+960" },
            new Country { CountryEnName = "Mali", CountryArName = "مالي", Code = "+223" },
            new Country { CountryEnName = "Malta", CountryArName = "مالطا", Code = "+356" },
            new Country { CountryEnName = "Marshall Islands", CountryArName = "جزر مارشال", Code = "+692" },
            new Country { CountryEnName = "Martinique", CountryArName = "مارتينيك", Code = "+596" },
            new Country { CountryEnName = "Mauritania", CountryArName = "موريتانيا", Code = "+222" },
            new Country { CountryEnName = "Mauritius", CountryArName = "موريشيوس", Code = "+230" },
            new Country { CountryEnName = "Mayotte", CountryArName = "مايوت", Code = "+262" },
            new Country { CountryEnName = "Mexico", CountryArName = "المكسيك", Code = "+52" },
            new Country { CountryEnName = "Micronesia", CountryArName = "ميكرونيزيا", Code = "+691" },
            new Country { CountryEnName = "Moldova", CountryArName = "مولدوفا", Code = "+373" },
            new Country { CountryEnName = "Monaco", CountryArName = "موناكو", Code = "+377" },
            new Country { CountryEnName = "Mongolia", CountryArName = "منغوليا", Code = "+976" },
            new Country { CountryEnName = "Montenegro", CountryArName = "الجبل الأسود", Code = "+382" },
            new Country { CountryEnName = "Morocco", CountryArName = "المغرب", Code = "+212" },
            new Country { CountryEnName = "Mozambique", CountryArName = "موزمبيق", Code = "+258" },
            new Country { CountryEnName = "Myanmar", CountryArName = "ميانمار", Code = "+95" },
            new Country { CountryEnName = "Namibia", CountryArName = "ناميبيا", Code = "+264" },
            new Country { CountryEnName = "Nauru", CountryArName = "ناورو", Code = "+674" },
            new Country { CountryEnName = "Nepal", CountryArName = "نيبال", Code = "+977" },
            new Country { CountryEnName = "Netherlands", CountryArName = "هولندا", Code = "+31" },
            new Country { CountryEnName = "New Caledonia", CountryArName = "كاليدونيا الجديدة", Code = "+687" },
            new Country { CountryEnName = "New Zealand", CountryArName = "نيوزيلندا", Code = "+64" },
            new Country { CountryEnName = "Nicaragua", CountryArName = "نيكاراغوا", Code = "+505" },
            new Country { CountryEnName = "Niger", CountryArName = "النيجر", Code = "+227" },
            new Country { CountryEnName = "Nigeria", CountryArName = "نيجيريا", Code = "+234" },
            new Country { CountryEnName = "North Korea", CountryArName = "كوريا الشمالية", Code = "+850" },
            new Country { CountryEnName = "North Macedonia", CountryArName = "مقدونيا الشمالية", Code = "+389" },
            new Country { CountryEnName = "Northern Mariana Islands", CountryArName = "جزر ماريانا الشمالية", Code = "+1670" },
            new Country { CountryEnName = "Norway", CountryArName = "النرويج", Code = "+47" },
            new Country { CountryEnName = "Oman", CountryArName = "سلطنة عمان", Code = "+968" },
            new Country { CountryEnName = "Pakistan", CountryArName = "باكستان", Code = "+92" },
            new Country { CountryEnName = "Palau", CountryArName = "بالاو", Code = "+680" },
            new Country { CountryEnName = "Palestine", CountryArName = "فلسطين", Code = "+970" },
            new Country { CountryEnName = "Panama", CountryArName = "بنما", Code = "+507" },
            new Country { CountryEnName = "Papua New Guinea", CountryArName = "بابوا غينيا الجديدة", Code = "+675" },
            new Country { CountryEnName = "Paraguay", CountryArName = "باراغواي", Code = "+595" },
            new Country { CountryEnName = "Peru", CountryArName = "بيرو", Code = "+51" },
            new Country { CountryEnName = "Philippines", CountryArName = "الفلبين", Code = "+63" },
            new Country { CountryEnName = "Poland", CountryArName = "بولندا", Code = "+48" },
            new Country { CountryEnName = "Portugal", CountryArName = "البرتغال", Code = "+351" },
            new Country { CountryEnName = "Puerto Rico", CountryArName = "بورتوريكو", Code = "+1787" },
            new Country { CountryEnName = "Qatar", CountryArName = "قطر", Code = "+974" },
            new Country { CountryEnName = "Reunion", CountryArName = "ريونيون", Code = "+262" },
            new Country { CountryEnName = "Romania", CountryArName = "رومانيا", Code = "+40" },
            new Country { CountryEnName = "Russia", CountryArName = "روسيا", Code = "+7" },
            new Country { CountryEnName = "Rwanda", CountryArName = "رواندا", Code = "+250" },
            new Country { CountryEnName = "Saint Kitts and Nevis", CountryArName = "سانت كيتس ونيفيس", Code = "+1869" },
            new Country { CountryEnName = "Saint Lucia", CountryArName = "سانت لوسيا", Code = "+1758" },
            new Country { CountryEnName = "Saint Martin", CountryArName = "سان مارتين", Code = "+590" },
            new Country { CountryEnName = "Saint Vincent and the Grenadines", CountryArName = "سانت فنسنت والغرينادين", Code = "+1784" },
            new Country { CountryEnName = "Samoa", CountryArName = "ساموا", Code = "+685" },
            new Country { CountryEnName = "San Marino", CountryArName = "سان مارينو", Code = "+378" },
            new Country { CountryEnName = "Sao Tome and Principe", CountryArName = "ساو تومي وبرينسيب", Code = "+239" },
            new Country { CountryEnName = "Saudi Arabia", CountryArName = "المملكة العربية السعودية", Code = "+966" },
            new Country { CountryEnName = "Senegal", CountryArName = "السنغال", Code = "+221" },
            new Country { CountryEnName = "Serbia", CountryArName = "صربيا", Code = "+381" },
            new Country { CountryEnName = "Seychelles", CountryArName = "سيشل", Code = "+248" },
            new Country { CountryEnName = "Sierra Leone", CountryArName = "سيراليون", Code = "+232" },
            new Country { CountryEnName = "Singapore", CountryArName = "سنغافورة", Code = "+65" },
            new Country { CountryEnName = "Sint Maarten", CountryArName = "سينت مارتن", Code = "+1721" },
            new Country { CountryEnName = "Slovakia", CountryArName = "سلوفاكيا", Code = "+421" },
            new Country { CountryEnName = "Slovenia", CountryArName = "سلوفينيا", Code = "+386" },
            new Country { CountryEnName = "Solomon Islands", CountryArName = "جزر سليمان", Code = "+677" },
            new Country { CountryEnName = "Somalia", CountryArName = "الصومال", Code = "+252" },
            new Country { CountryEnName = "South Africa", CountryArName = "جنوب أفريقيا", Code = "+27" },
            new Country { CountryEnName = "South Korea", CountryArName = "كوريا الجنوبية", Code = "+82" },
            new Country { CountryEnName = "South Sudan", CountryArName = "جنوب السودان", Code = "+211" },
            new Country { CountryEnName = "Spain", CountryArName = "إسبانيا", Code = "+34" },
            new Country { CountryEnName = "Sri Lanka", CountryArName = "سريلانكا", Code = "+94" },
            new Country { CountryEnName = "Sudan", CountryArName = "السودان", Code = "+249" },
            new Country { CountryEnName = "Suriname", CountryArName = "سورينام", Code = "+597" },
            new Country { CountryEnName = "Sweden", CountryArName = "السويد", Code = "+46" },
            new Country { CountryEnName = "Switzerland", CountryArName = "سويسرا", Code = "+41" },
            new Country { CountryEnName = "Syria", CountryArName = "سوريا", Code = "+963" },
            new Country { CountryEnName = "Taiwan", CountryArName = "تايوان", Code = "+886" },
            new Country { CountryEnName = "Tajikistan", CountryArName = "طاجيكستان", Code = "+992" },
            new Country { CountryEnName = "Tanzania", CountryArName = "تنزانيا", Code = "+255" },
            new Country { CountryEnName = "Thailand", CountryArName = "تايلاند", Code = "+66" },
            new Country { CountryEnName = "Timor-Leste", CountryArName = "تيمور الشرقية", Code = "+670" },
            new Country { CountryEnName = "Togo", CountryArName = "توغو", Code = "+228" },
            new Country { CountryEnName = "Tonga", CountryArName = "تونغا", Code = "+676" },
            new Country { CountryEnName = "Trinidad and Tobago", CountryArName = "ترينيداد وتوباغو", Code = "+1868" },
            new Country { CountryEnName = "Tunisia", CountryArName = "تونس", Code = "+216" },
            new Country { CountryEnName = "Turkey", CountryArName = "تركيا", Code = "+90" },
            new Country { CountryEnName = "Turkmenistan", CountryArName = "تركمانستان", Code = "+993" },
            new Country { CountryEnName = "Turks and Caicos Islands", CountryArName = "جزر توركس وكايكوس", Code = "+1649" },
            new Country { CountryEnName = "Tuvalu", CountryArName = "توفالو", Code = "+688" },
            new Country { CountryEnName = "Uganda", CountryArName = "أوغندا", Code = "+256" },
            new Country { CountryEnName = "Ukraine", CountryArName = "أوكرانيا", Code = "+380" },
            new Country { CountryEnName = "United Arab Emirates", CountryArName = "الإمارات العربية المتحدة", Code = "+971" },
            new Country { CountryEnName = "United Kingdom", CountryArName = "المملكة المتحدة", Code = "+44" },
            new Country { CountryEnName = "United States", CountryArName = "الولايات المتحدة", Code = "+1" },
            new Country { CountryEnName = "United States Virgin Islands", CountryArName = "جزر العذراء الأمريكية", Code = "+1340" },
            new Country { CountryEnName = "Uruguay", CountryArName = "أوروغواي", Code = "+598" },
            new Country { CountryEnName = "Uzbekistan", CountryArName = "أوزبكستان", Code = "+998" },
            new Country { CountryEnName = "Vanuatu", CountryArName = "فانواتو", Code = "+678" },
            new Country { CountryEnName = "Vatican City", CountryArName = "الفاتيكان", Code = "+379" },
            new Country { CountryEnName = "Venezuela", CountryArName = "فنزويلا", Code = "+58" },
            new Country { CountryEnName = "Vietnam", CountryArName = "فيتنام", Code = "+84" },
            new Country { CountryEnName = "Yemen", CountryArName = "اليمن", Code = "+967" },
            new Country { CountryEnName = "Zambia", CountryArName = "زامبيا", Code = "+260" },
            new Country { CountryEnName = "Zimbabwe", CountryArName = "زيمبابوي", Code = "+263" }
        };
    }
}
