<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Stock_Exchange.Infrastructure</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Stock-Exchange.Application\Stock-Exchange.Application.csproj" />
    <ProjectReference Include="..\Stock-Exchange.Persistance\Stock-Exchange.Persistance.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Repositories\Implementations\" />
  </ItemGroup>

</Project>
